### ISSUE TITLE
New workspace only if no empty

### ISSUE THREAD

**Issue by boogiefromzk** [rliang/gnome-shell-extension-maximize-to-workspace#1]
I have a problem with this cool extension: some shitty app is opening and hiding tons of windows (still can't get what it is), but this extension opens hundreds of empty workspaces and makes x server hang.
The good solution is to put new windows to empty workspaces instead of simply putting to a new one each time. At least not adding a new workspace if the last one existing is empty.

**Comment by rliang** [comment]
Hi, it's been a while since this issue was opened. I'll close this for now but please tell if the issue persists by installing from the latest source.
