### ISSUE TITLE
Please update to 3.34 and beyond.

### ISSUE THREAD

**Issue by SaucySauce** [rliang/gnome-shell-extension-maximize-to-workspace#10]
While the extension does its job fine on 3.34, it'll over time start having erratic animations when the program is opening and the interface of it becomes a frozen opening animation requiring the program to be closed and opened again.

**Comment by lfom** [comment]
Actually, it seems that there is some timing issues: if animations is enabled, it may cause problems in how Gnome Shell handles windows (maximizing, changing workspace, etc) while the extension is moving things around... This kind of error can be seen in the log:
```
g_hash_table_iter_next: assertion 'ri->version == ri->hash_table->version' failed
```
