### ISSUE TITLE
Add github link to extensions.gnome.org

### ISSUE THREAD

**Issue by bulletmark** [rliang/gnome-shell-extension-maximize-to-workspace#2]
Normally the source home page/repository should stated as a link on the extensions homepage on https://extensions.gnome.org/extension/1181/maximize-to-workspace/ so people can quickly find the source and issues list etc. Three months ago you stated there in a comment response there that you would add this but it appears you have forgotten.

Great extension BTW. This is a nice feature from Mac OS X which I was missing and I am surprised this extension is not more widely appreciated.

**Comment by rliang** [comment]
Done 👍

**Comment by bulletmark** [comment]
I don't see a commit to add the url to metadata.json, nor anywhere else? Nor is it added on extensions.gnome.org? What did you actually do?

**Comment by rliang** [comment]
Oh, my mistake, I actually put it on README.md not metadata.json, now fixed.
