### ISSUE TITLE
Cheese crashes with this extension!

### ISSUE THREAD

**Issue by aviwad** [rliang/gnome-shell-extension-maximize-to-workspace#3]
Cheese creates a pure white window when an image gets taken, and that bugs this extension into crashing the whole gnome desktop! 
This bug is pure nasty!

**Comment by rliang** [comment]
Hi,

Although Cheese gets mistakenly sent to another workspace, it doesn't crash here. Does `journalctl /usr/bin/gnome-shell` report any errors about the extension?

**Comment by aviwad** [comment]
wait, i think i know why cheese isn't crashing for you. 
do this.
1. open any app in maxmised in workspace 1
2. open cheese in unmaximised form in same workspace
3. make sure "Fire Flash" is turned on in Cheese (on by default)
4. try taking a picture :smile: 
5. the screen goes flash white, and then gnome either restarts with your open apps still open, or you get logged out

**Comment by rliang** [comment]
Still not crashing. What GNOME version?

**Comment by aviwad** [comment]
3.24 in Solus GNOME

**Comment by aviwad** [comment]
Hold on, when i reach home (in 7 hours) I will send you a screen cast

**Comment by rliang** [comment]
Alright, I got to reproduce the issue.

Fortunately, it's already fixed in the latest git commit, so you can just install from source to fix it on your end, until the latest version lands on the GNOME extensions page.
