### ISSUE TITLE
**FEATURE REQUEST**

### ISSUE THREAD

**Issue by aviwad** [rliang/gnome-shell-extension-maximize-to-workspace#4]
Expected behavior: if an app is maximised in a workspace, no other app should be able to live in the same workspace, maximised or not. somewhat like macOS

Actual behavior: nothing of the above

It would be nice to have this as an option!

GNOME version: 3.24

**Comment by rliang** [comment]
Well, this is all the extension should do. If not, clearly there's a bug happening.

Does the command `journalctl /usr/bin/gnome-shell` output any errors about the extension?

**Comment by rliang** [comment]
Probably duplicate of #3

**Comment by aviwad** [comment]
What? no. I mean, even when your extension works, I can easily put another window in the same workspace as a maximized window. so i wanted a feature request, that a workspace with a maximized window can not have any other windows on it. I just wanted it to be a little more like macOS
