### ISSUE TITLE
Move windows to first workspace on restore

### ISSUE THREAD

**Issue by kushalchauhan98** [rliang/gnome-shell-extension-maximize-to-workspace#8]
### Expected behavior
In MacOS, when a window is restored, it is moved to the first workspace where all non-maximized windows reside.
### Actual behavior
When a maximized window is restored, it stays in the different workspace that it was in before.
### (Recommended) GNOME version
3.28

Great work, by the way!

**Comment by ysolis** [comment]
one alternative can be to define specific workspaces similar to AutoMoveWindow extension (https://extensions.gnome.org/extension/16/auto-move-windows/) and that the unmaximized windows share by default one workspace for all the unmaximized windows (the first or the last workspace). if one app/window is not associated to one workspace, create a new workspace to this.

**Comment by lfom** [comment]
WIP...

![Screenshot from 2020-09-10 00-53-58](https://user-images.githubusercontent.com/15659999/92680551-7adc5b80-f301-11ea-9032-6d7225ef83b0.png)

**Comment by aviwad** [comment]
> WIP...
> 

Incredible! Where could I find this WIP build? It is not available on your GitHub profile, nor as a branch anywhere :thinking:

**Comment by lfom** [comment]
I will send a PR soon, hopefully. And get some feedback from the features...

**Comment by aviwad** [comment]
Great. Can't wait

**Comment by lfom** [comment]
I have pushed to my fork dev tree:
https://github.com/lfom/gnome-shell-extension-maximize-to-workspace/tree/dev

All features shown in the screenshot were implemented, there are many `log` calls that I need until the code is ready for PR (some refactoring and new modules to streamline the main JS file, and make it more readable for future improvements).

**Comment by whoamiUNIX** [comment]
> WIP...
> 
> ![Screenshot from 2020-09-10 00-53-58](https://user-images.githubusercontent.com/15659999/92680551-7adc5b80-f301-11ea-9032-6d7225ef83b0.png)

would be perfect to have this feature ... I stop using this plugin because this function is missing here. 
+100 from my side.

**Comment by whoamiUNIX** [comment]
@lfom anything new ? :-)

**Comment by lfom** [comment]
> I have pushed to my fork dev tree:
> https://github.com/lfom/gnome-shell-extension-maximize-to-workspace/tree/dev

It is available in the place above. I am waiting for some feedback, if there is no major problems I will prepare the code for a PR.

**Comment by whoamiUNIX** [comment]
@lfom
-  Thank you so much it works perfectly. Great job +100. Restore mode is perfect. Now this extension is so effective. 
![image](https://user-images.githubusercontent.com/40315055/97230429-3259fe00-17da-11eb-8ea0-a992ba17916b.png)

- Only what I do not like is that effect how it move and how it move back but this is only details from my perspective. Also I see that when I maximize it take some delay until is maximized and moved it is possible to do quicker ? If yes maybe could be possible set this speed. If not that is fine. Now this extension works perfectly. I think you can do PR.

**Comment by lfom** [comment]
IIRIC there is no code related to the animation, or how long it lasts... You can disable animations in Gnome Tweaks, or use some extension like Impatience to speed things up.

**Comment by whoamiUNIX** [comment]
Sure then it works perfectly. Let me know if you need something else before you will do PR. Tested on:

```
OS: Ubuntu 20.04.1 LTS
OS type: 64-bit
Gnome version: 3.36.3
Windowing system: x11
Kernel: 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by lfom** [comment]
> * Only what I do not like is that effect how it move and how it move back but this is only details from my perspective. Also I see that when I maximize it take some delay until is maximized and moved it is possible to do quicker ?

Actually, there is a delay in the code. It is needed if animations are enabled: if the extension tries to move/resize the window while the animation is going on, it will mess with Gnome Shell logic and probably crash it at some point. But the new code reads this information from Mutter settings, so it should be faster when animations are disabled or shorter.
